# Configuration for deploying an API Gateway without elasticsearch to a kubernetes cluster.
# An external elasticsearch needs to be up and running.
# The cluster should provide at least 4 GB of main memory.
#
# The full documentation is available from the Software AG Documentation website: 
# http://techcommunity.softwareag.com/ecosystem/documentation/webmethods/api_gateway/yai10-4/index.htm
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment-external-es
  labels:
    app: api-gateway-deployment-external-es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-deployment-external-es
  template:
    metadata:
      labels:
        app: api-gateway-deployment-external-es
    spec:
      containers:
      - name: api-gateway-deployment-external-es
        # Please fill in the path to your api gateway image stored in a docker registry.
        image: <yourDockerRegistry>:<RegistryPort>/<PathToApiGateway>:<Tag>
        # The default pull policy is IfNotPresent which causes the Kubelet to skip pulling an image if it already exists.
        # If you would like to always force a pull use "Always"        
        imagePullPolicy: IfNotPresent
        env:
        # Please fill in your datas to access your external elasticsearch.
        # Url pointing to your running elasticsearch for example: 127.0.0.1:9200
        - name: apigw_elasticsearch_hosts
          value: "<UrlToYourExternalElasticsearch>:<elasticsearchPort>"
        # Use true if your elasticsearch has https enabled, false if not.
        - name: "apigw_elasticsearch_https_enabled"
          value: <"false" or "true">
        # Fill in your elasticsearch username for example: elastic
        - name: "apigw_elasticsearch_http_username"
          value: <elasticsearchUsername>
        # Fill in your elasticsearch password for example: changeme
        - name: "apigw_elasticsearch_http_password"
          value: <elasticsearchPassword>
        # Ports used in the docker image, the default ports are 5555 and 9072
        ports:
        - containerPort: 5555
          name: 5555tcp01
          protocol: TCP
        - containerPort: 9072
          name: 9072tcp01
          protocol: TCP
        livenessProbe:
          failureThreshold: 4
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5555
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /rest/apigateway/health
            port: 5555
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 2
          timeoutSeconds: 2
---
# An example service for the deployment above.
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app.kubernetes.io/name: api-gateway-deployment
spec:
  type: NodePort
  ports:
    - name: http1
      port: 5555
      targetPort: 5555
      protocol: TCP 
    - name: http2
      port: 9072
      targetPort: 9072
      protocol: TCP 
  selector:
    app: api-gateway-deployment